### PR TITLE
Packages (Linux): fixes Linglong detection by counting linglong layers 

### LINKED ISSUE #1898: [Bug] Linglong detection fails on Debian 13 for installations from Deepin's repository
**Bug Description**

Fastfetch does not detect Linglong packages on a Debian 13 "Trixie" system when Linglong is installed from a third-party repository provided by the Deepin team. This issue persists even with the latest Fastfetch version (2.50.0).

**To Reproduce**

1.  Start with a clean Debian 13 "Trixie" system.
2.  Add the Deepin Linglong repository using the following command:
    ```sh
    echo "deb [trusted=yes] [https://ci.deepin.com/repo/obs/linglong:/CI:/release/Debian_13/](https://ci.deepin.com/repo/obs/linglong:/CI:/release/Debian_13/) ./" | sudo tee /etc/apt/sources.list.d/linglong.list
    ```
3.  Update the package list and install the Linglong components:
    ```sh
    sudo apt update
    sudo apt install linglong-bin linglong-box linglong-builder
    ```
4.  Install at least one Linglong application, for example, WeChat:
    ```sh
    ll-cli install com.tencent.wechat
    ```
5.  Install or update to the latest version of Fastfetch. In my case, I upgraded from the Debian repo version (`2.40.4`) to the latest release from GitHub (`2.50.0`).
    ```
    glqyu@GLQY-Debian:~$ fastfetch --version
    fastfetch 2.50.0 (x86_64)
    ```
6.  Run `fastfetch`.

**Expected Behavior**

The `Packages:` line in the `fastfetch` output should include a count for Linglong, for example:
`Packages: 3369 (dpkg), 11 (flatpak), 2 (linglong)`

**Actual Behavior**

The `Linglong` count is completely missing from the output.

**System Information (output from `fastfetch`)**

````

OS: Debian GNU/Linux 13 (trixie) x86\_64
Host: ASUS TUF Gaming A15 FA506QM\_FA506QM (1.0)
Kernel: Linux 6.12.38+deb13-amd64
Uptime: 1 hour, 8 mins
Packages: 3369 (dpkg), 11 (flatpak)
Shell: bash 5.2.37
DE: KDE Plasma 6.3.6
WM: KWin (Wayland)
... (and other system details)

````

**Investigation and Findings**

I have confirmed that the detection is failing because this Linglong installation uses a different path than the one Fastfetch currently checks.

First, I listed my installed Linglong packages, confirming two are present:

```sh
$ ll-cli list
ID                      Name                    Version         Channel         Arch            Description
com.tencent.wechat      WeChat(Test Version)    4.0.1.13        main            binary          The Tencent WeChat Linux official version
org.deepin.base         deepin-base             25.2.0.92       main            binary          deepin base environment.
````

Then, I directly checked the path that the Fastfetch source code uses for detection (`/var/lib/linglong/repo/refs/heads/main`) and confirmed it is empty on my system, while the `remotes` directory exists alongside it:

```bash
$ ls /var/lib/linglong/repo/refs/heads/main
ls: cannot access '/var/lib/linglong/repo/refs/heads/main': No such file or directory

$ ls /var/lib/linglong/repo/refs
heads   mirrors   remotes
```

Finally, I used `find` to locate the package files, which confirms they are under the `remotes/stable/main` subdirectory:

```bash
$ sudo find / -name "*org.deepin.base*"
find: ‘/run/user/1000/doc’: Permission denied
/var/lib/linglong/repo/refs/remotes/stable/main/org.deepin.base
/var/lib/linglong/layers/0286c7ff50b7246d0583675a5c9fbf2fa601373f5f34439dec05b5f70ab145ea/org.deepin.base.install
```

This demonstrates that the Linglong applications and their metadata are located under the `.../repo/refs/remotes/stable/main` path, not the `.../repo/refs/heads/main` path that Fastfetch's logic currently relies on. The detection logic needs to be updated to check this alternative path as well.

Thank you for creating such a great tool\!

### PR DESCRIPTION
**Pull request by GuilingQiyu**
Fixes #1898 
Count linglong layers to achieve a robuster linglong packages detection

### CODE REVIEW

File: src/detection/packages/packages_linux.c [hunk 1]
```diff
@@ -446,12 +446,7 @@ static void getPackageCounts(FFstrbuf* baseDir, FFPackagesResult* packageCounts,
     {
       packageCounts->guixSystem += getGuixPackages(baseDir, "/run/current-system/profile");
     }
-    if (!(options->disabled & FF_PACKAGES_FLAG_LINGLONG_BIT))
-    {
-        packageCounts->linglong += getNumElements(baseDir, "/var/lib/linglong/repo/refs/heads/main", true);
-        if (packageCounts->linglong == 0)
-            packageCounts->linglong += getNumElements(baseDir, "/var/lib/linglong/repo/refs/remotes/stable/main", true);
-    }
+    if (!(options->disabled & FF_PACKAGES_FLAG_LINGLONG_BIT))packageCounts->linglong += getNumElements(baseDir, "/var/lib/linglong/layers", true);
```
Comment (CarterLi) [inline src/detection/packages/packages_linux.c]:
```suggestion
    if (!(options->disabled & FF_PACKAGES_FLAG_LINGLONG_BIT)) packageCounts->linglong += getNumElements(baseDir, "/var/lib/linglong/layers", true);
```

**Comment by CarterLi** [comment]
Did you test Deepin?
